### ISSUE TITLE
Error while try access DNS

### ISSUE THREAD

**Issue by brunowego** [rpardini/docker-registry-proxy#12]
I'm getting error in output of docker log:

```sh
2019/06/27 12:00:40 [error] 105#105: recv() failed (111: Connection refused) while resolving, resolver: 10.254.1.193:53
```

When run a docker pull:

```
$ time docker pull k8s.gcr.io/kube-proxy-amd64:v1.10.4                                                                                                                            9:00:15
Error response from daemon: error unmarshalling content: invalid character 'd' looking for beginning of value
docker pull k8s.gcr.io/kube-proxy-amd64:v1.10.4  0.06s user 0.03s system 0% cpu 27.377 total
```

Did you have a tip for solve this issue?

**Comment by rpardini** [comment]
Your DNS is not working inside the container, probably due to some corporate firewall policy or whatnot.
There was some work done previously to allow for this scenario, check https://github.com/rpardini/docker-registry-proxy/pull/7 (eg, try mounting `/etc/nginx/resolvers.conf` or something to that effect)
