### ISSUE TITLE
How to configure containerd?

### ISSUE THREAD

**Issue by markbaumgarten** [rpardini/docker-registry-proxy#129]
Kubernetes seems to be moving away from docker and towards containerd.

Does anyone have an example showing how to setup containerd for this registry-proxy to work - preferably using a k8s DeamonSet ?

**Comment by rpardini** [comment]
Yes, it's working with containerd. 
The same principles (https_proxy, mitm certs) used for dockerd can be used for containerd, but you can also use containerd's toml configs to fine tune stuff that was not possible in docker case.
I have not had time to write up documentation, indeed all docs we have here were written by contributors, so please send PRs.

**Comment by jorge07** [comment]
My initial attempt is failing sue to incorrect media type, so, not a drop in replacement ATM

```

**Comment by ericazhao-china** [comment]
Do we have further update for supporting containerd as container runtime in cloud provider kubernetes cluster? 

I tried in IBM Cloud IKS cluster with Containerd . 
1. deploy the daemonset  on worker node  , service  expose 3128 port 

apiVersion: apps/v1
kind: DaemonSet
metadata:
name: docker-registry-proxy
spec:
selector:
matchLabels:
app: docker-registry-proxy
updateStrategy:
rollingUpdate:
maxSurge: 0
maxUnavailable: 100%
type: RollingUpdate
template:
metadata:
labels:
app: docker-registry-proxy
spec:
terminationGracePeriodSeconds: 360
containers:
- env:
image: rpardini/docker-registry-proxy:0.6.2
imagePullPolicy: Always
name: docker-registry-proxy
resources: {}
env:
- name: ENABLE_MANIFEST_CACHE
value: "true"
- name: REGISTRIES
value: "quay.io na.artifactory.taas.kyndryl.net"
volumeMounts:
- mountPath: /docker_mirror_cache
name: docker-mirror-cache-volume
- mountPath: /ca
name: proxy-ca-volume
restartPolicy: Always
volumes:
- name: docker-mirror-cache-volume
hostPath:
# directory location on host
path: /docker_mirror_cache
# this field is optional
type: ""
- name: proxy-ca-volume
hostPath:
# directory location on host
path: /docker_mirror_certs
# this field is optional
type: ""
status:
currentNumberScheduled: 1
desiredNumberScheduled: 1
numberAvailable: 1
numberMisscheduled: 0
numberReady: 1
observedGeneration: 1
updatedNumberScheduled: 1

apiVersion: v1
kind: Service
metadata:
name: docker-registry-proxy-svc
spec:
selector:
app: docker-registry-proxy
ports:
- protocol: TCP
port: 3128
targetPort: 3128



2. As in IBM cloud , i can't ssh into the worker node instead of i can use debug pod with root permission to add some config file 

# cat /host/etc/systemd/system/containerd.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://172.21.188.243:3128/"
Environment="HTTPS_PROXY=http://172.21.188.243:3128/"

# ls /host/etc/containerd/certs.d/
docker.io   quay.io

# cat /host/etc/containerd/certs.d/quay.io/hosts.toml
server = "https://quay.io"
[host."https://quay.io"]
  capabilities = ["pull", "resolve"]

As this registry.mirror  in Containerd config file already deprecated in Containerd (containerd registry of mirror has been DEPRECATED https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-endpoint)  , so it's not working and also found some issue for registry mirror can't fall back to upstream repo https://github.com/containerd/containerd/issues/7321  https://github.com/containerd/containerd/issues/4531 


### UBUNTU
# Get the CA certificate from the proxy and make it a trusted root.
curl http://<service-cluster-ip>:3128/ca.crt > /usr/share/ca-certificates/docker_registry_proxy.crt
echo "docker_registry_proxy.crt" >> /etc/ca-certificates.conf
update-ca-certificates --fresh
###

After all above configuration , as inside of debug pod  we can't find  a way (shouldn't support) to restart containerd service , and in this case verify using a pod to pull image from quay.io of calico-etcd image, it's not working and not cached in proxy .
