### ISSUE TITLE
Using upstream proxy

### ISSUE THREAD

**Issue by kovaxur** [rpardini/docker-registry-proxy#23]
Hi,
It would be nice to be able to use an upstream proxy, this can be interesting, when someone has a company proxy towards the internet.

So something like this:
```
docker_host1 ---
                + --> docker-registry-proxy --> company_proxy --> internet
docker_host2 ---
```

**Comment by rpardini** [comment]
Pull requests are welcome!

**Comment by ahmadalli** [comment]
I've tried adding proxy via changing nginx configs to this:

```conf
rewrite ^(.*)$ ://$targetHost$1;
rewrite ^(.*)$ https$1 break;
proxy_set_header Host $targetHost;
proxy_pass http://1.2.3.4:1234;
```

with no success. Becase nginx tries simple `GET https://...` on the proxy server which is not possible since the host requires tls handshake

**Comment by ahmadalli** [comment]
I ended up having a messy solution for this. since nginx requires https proxy for the matter, I'm setting up two docker-registry-proxy, one in the production zone (better connectivity and faster network but no outside internet access) which caches everything, and one other docker-registry-proxy on the outside node which just acts as a passthrough proxy.

I've tried this simple config on `nginx:alpine` but for some reason, download speed was very low:

```nginx
server {
  listen 443 ssl default_server;
  ssl_certificate /certs/cert.crt;
  ssl_certificate_key /certs/key.pem;

  access_log  /var/log/nginx/access.log  tweaked;
  chunked_transfer_encoding on;
  proxy_read_timeout 900;
  proxy_ssl_server_name on;
  proxy_pass_request_headers on;

  # dns resolver used by forward proxying
  resolver  1.1.1.1;

  # forward proxy for non-CONNECT request
  location / {
    proxy_pass https://$host;
    proxy_set_header Host $host;
  }
}
```

so I installed docker-registry-proxy on the node and changed the `nginx.conf` file and removed all the `proxy_cache` related configs from it and I was able to reach a good download speed with this solution
